[pytest]
addopts = -rA -n auto --headed --browser chromium --browser-channel chrome
python_files = test_*.py
python_functions = test_*
testpaths = tests

markers =
    smoke: smoke tests
    afex: AFEX related tests
    login: login-related scenarios
    dataDriven: data-driven BDD scenarios
